###
GET  https://bitbucket.com/rest/api/1.0/projects/${project}/repos/${repository}/commits?until=${branch}
Authorization: Bearer xxx
Content-Type: application/json

###
GET  https://bitbucket.com/rest/api/1.0/projects/${project}/repos
Authorization: Bearer xxx
Content-Type: application/json

###
POST http://localhost:3000/hashes/${project}
Content-Type: application/json

{
  "release": "${branch}",
  "services": [
    "${service_1}",
    "${service_2}"
  ]
}
